name: Caller workflow
on:
  push:
    tags:
      - reusable_workflow

jobs:
  some-job:
    name: Some job
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Prepare git
        run: |
          git config --global user.email "ca@kode.ru"
          git config --global user.name "ca"
          git fetch
          git checkout main
          git push --delete origin $GITHUB_REF_NAME
          git tag -d $GITHUB_REF_NAME

      - name: Run reusable workflow
        uses: ./callable_workflow.yml
        with:
          SOME_INPUT: test input
        secrets: inherit
