name: Callable workflow
on:
  workflow_call:
    inputs:
      SOME_INPUT:
        required: true
        type: string

jobs:
  reusable-job:
    name: Reusable job
    runs-on: ubuntu-latest
    steps:
      - name: Run reusable workflow
        run: |
          echo "SOME_INPUT=${{ inputs.SOME_INPUT }}"
          echo "SECRET_INHERIT=${{ secrets.SECRET }}"

