name: Callable workflow
on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
      SOME_INPUT:
        required: true
        type: string

jobs:
  reusable-job:
    name: Reusable job
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    steps:
      - name: Run reusable workflow
        run: |
          echo "SOME_INPUT=${{ inputs.SOME_INPUT }}"
          echo "SECRET=${{ secrets.SECRET }}"
          echo "VARIABLE=${{ vars.VARIABLE }}"

          if [ "${{ secrets.SECRET }}" == "123" ]; then
            echo "Stage secret"
          else
            echo "Not matched stage"
          fi

          if [ "${{ secrets.SECRET }}" == "321" ]; then
            echo "Prod secret"
          else
            echo "Not matched prod"
          fi

          if [ "${{ secrets.COMMON_SECRET }}" == "test" ]; then
            echo "COMMON_SECRET secret"
          else
            echo "Not matched COMMON_SECRET"
          fi

