name: Caller workflow
on:
  push:
    tags:
      - reusable_workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  git:
    name: Git
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove release if needed
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: $GITHUB_REF_NAME
          suppress_errors: true

  some-job:
    name: Some job
    needs: [git]
    if: success()
    strategy:
      matrix:
        target: [Stage, Prod]
    uses: ./.github/workflows/callable_workflow.yml
    with:
      SOME_INPUT: test input
      ENV: ${{ matrix.target }}
    secrets: inherit
