name: Caller workflow
on:
  push:
    tags:
      - reusable_workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  git:
    name: Git
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove release if needed
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: $GITHUB_REF_NAME
          suppress_errors: true
          
      - name: Prepare git
        run: |
          git config --global user.email "ca@kode.ru"
          git config --global user.name "ca"
          git fetch
          git checkout main
          git push --delete origin $GITHUB_REF_NAME
          git tag -d $GITHUB_REF_NAME

  some-job:
    name: Some job
    needs: [git]
    if: success()
    uses: ./.github/workflows/callable_workflow.yml
    with:
      SOME_INPUT: test input
    secrets: inherit
