name: Caller workflow
on:
  push:
    tags:
      - reusable_workflow

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  git:
    name: Git
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove release if needed
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: $GITHUB_REF_NAME
          suppress_errors: true

  some-job-stage:
    name: Some job Stage
    needs: [git]
    if: success()
    uses: ./.github/workflows/callable_workflow.yml
    with:
      SOME_INPUT: test input
      ENV: Stage

  some-job-prod:
    name: Some job Prod
    needs: [git]
    if: success()
    uses: ./.github/workflows/callable_workflow.yml
    with:
      SOME_INPUT: test input
      ENV: Prod
